name              'munin'
maintainer        'Jesse R. Adams'
maintainer_email  'jesse@techno-geeks.org'
license           'Apache-2.0'
description       'Installs and configures munin'
version           '3.0.0'

depends 'apache2', '>= 1.7'
depends 'nginx', '>= 10.3.1'

supports 'arch'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'freebsd'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
